version: '3.7'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=db_challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data
  springboot:
    restart: always
    build: .
    container_name: springboot
    working_dir: /opt/app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  database_data:
    driver: local